version: 1
disable_existing_loggers: False

formatters:
  consoleFormatter:
    format: '%(asctime)s | %(name)s | %(levelname)s : %(message)s'
  fileFormatter:
    format: '%(asctime)s | %(name)s | %(levelname)s : %(message)s'

handlers:
  file:
    filename: debug_yaml.log
    level: DEBUG
    class: logging.FileHandler
    formatter: fileFormatter
  console:
    level: CRITICAL
    class: logging.StreamHandler
    formatter: consoleFormatter

loggers:
  root:
    level: DEBUG
    handlers: [file, console]